version: '3.4'

services:
  app: &app
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '3.0.2-alpine'
        BUNDLER_VERSION: '2.1.4'
    image: rs:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    # command: tail -f /dev/null
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3000:3000'

  mysql:
    image: mysql:5.7
    volumes:
      - ./containers/db:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306

  webpacker:
    <<: *app
    stdin_open: true
    tty: true
    # command: ./bin/webpack-dev-server
    command: tail -f /dev/null
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  mysql:
  bundle:
  node_modules:
  rails_cache:
  packs:
