default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host:     <%= ENV['DATABASE_HOST'] %>
  database: rs
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket:   <%= ENV['DATABASE_SOCKET'] %>

development:
  <<: *default
  database: rs_development

test:
  <<: *default
  database: rs_test

production:
  <<: *default
<<<<<<< HEAD
=======
  database: rs_production
  pool: 20
>>>>>>> fbf36da6984512d8300281394ded38b212989388
  timeout: 1000
  database: rs_production
staging:
  <<: *default
  database: rs_staging
