default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host:     <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket:   <%= ENV['DATABASE_SOCKET'] %>

development:
  <<: *default

test:
  <<: *default
  database: rs_test

production:
  <<: *default
 database: test_app_production
 adapter: mysql2
 encoding: utf8mb4
 charset: utf8mb4
 collation: utf8mb4_general_ci
 encoding: unicode
 database: <%= Rails.application.credentials.db[:database] %>
 username: <%= Rails.application.credentials.db[:username] %>
 password: <%= Rails.application.credentials.db[:password] %>
 socket: <%= Rails.application.credentials.db[:socket] %>
 pool: 20
 timeout: 1000

staging:
  <<: *default
